---
title: "Untitled"
output: pdf_document
---


```{r}
library(feather)
library(tidyverse)
library(kableExtra)
ciuo <- read_feather("src/data/train_datasets/auditado_ciuo.feather")

```


```{r}
ciuo2 <- ciuo %>% 
  mutate(missing = case_when(
    b1_1 == "88" & b1_2 != "88" ~ "missing oficio",
    b1_1 != "88" & b1_2 == "88" ~ "missing tareas",
    b1_1 == "88" & b1_2 == "88" ~ "missing oficio y tareas",
    T ~ "válido"
    ) ) 

```


```{r, fig.align='center'}
footnote <- "Fuente: elaboración propia, Instituto Nacional de Estadísticas "

origen <- ciuo2 %>% 
        filter(missing == "válido") %>% 
        group_by(origen) %>% 
        summarise(frecuencia = n()) %>% 
        ungroup() %>% 
        mutate(total = sum(frecuencia),
               porcentaje = round(frecuencia / total * 100, 1),
               porcentaje = format(porcentaje ,decimal.mark=",",scientific=FALSE),
               frecuencia = format(frecuencia ,big.mark=".",scientific=FALSE)
               
               ) %>% 
        select(-total)

origen %>% 
  kbl(caption = "Origen de la codificación CIUO-08.CL", booktabs = T)  %>%
  kable_styling( font_size = 9.5 ) %>%
  footnote(general_title = "", general = footnote, footnote_as_chunk = T) 
```



```{r}
knitr::kable(origen, format = "latex", booktabs = TRUE, align=rep('c', 3)) %>%
          kable_styling(latex_options = c("HOLD_position"), font_size = 9.5) %>% 
  footnote(general_title = "", general = footnote, footnote_as_chunk = T) 
```
```





